# Generated by Django 4.2.4 on 2023-09-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0002_domain_description_alter_domain_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
