# Generated by Django 4.2.4 on 2023-09-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0003_alter_domain_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='links',
            field=models.CharField(default='', max_length=120),
        ),
    ]
