# Generated by Django 4.2.4 on 2023-09-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
    ]
